--DROP DATABASE PTTK_ABC;

CREATE DATABASE PTTK_ABC;
GO

USE PTTK_ABC;
GO

CREATE TABLE THANHVIEN (
  IdThanhVien INT IDENTITY(1,1) NOT NULL,
  TenDangNhap VARCHAR(30) UNIQUE,
  Ten VARCHAR(50),
  Email VARCHAR(30),
  MatKhau VARCHAR(20) NOT NULL,
  LoaiThanhVien VARCHAR(20),
  PRIMARY KEY (IdThanhVien)
);

CREATE TABLE DOANHNGHIEP (
  IdThanhVien INT PRIMARY KEY,
  MaSoThue INT,
  NguoiDaiDien VARCHAR(50),
  DiaChi VARCHAR(100),
  UuDai FLOAT
);

CREATE TABLE UNGVIEN (
  IdThanhVien INT PRIMARY KEY,
  NgaySinh DATE
);

CREATE TABLE NHANVIEN (
  IdThanhVien INT PRIMARY KEY,
  VaiTro VARCHAR(50) CHECK (VaiTro IN ('Ban Lãnh Đạo', 'Nhân Viên Cơ Bản'))
);

CREATE TABLE THANHTOAN (
  IdThanhToan INT IDENTITY(1,1) NOT NULL,
  NgayGiaoDich DATE,
  HinhThucTT VARCHAR(50),
  SoTienCanThanhToan BIGINT,
  Dot INT,
  IdHoaDon INT,
  PRIMARY KEY (IdThanhToan)
);

CREATE TABLE HOADON (
  IdHoaDon INT IDENTITY(1,1) NOT NULL,
  TongTien BIGINT,
  DaTra BIGINT,
  LoaiHinhThanhToan VARCHAR(50),
  NgayLap DATE,
  TrangThaiHoanThanh VARCHAR(50),
  IdDoanhNghiep INT,
  PRIMARY KEY (IdHoaDon)
);

CREATE TABLE HOSO (
  IdHoSo INT IDENTITY(1,1) NOT NULL,
  TinhTrang VARCHAR(50),
  IdThanhVien INT,
  PRIMARY KEY (IdHoSo)
);

CREATE TABLE BANGCAP (
  IdBang INT IDENTITY(1,1) NOT NULL,
  CapBac VARCHAR(50),
  NgayCap DATE,
  NoiCap VARCHAR(100),
  IdHoSo INT,
  PRIMARY KEY (IdHoSo)
);

CREATE TABLE UNGTUYEN (
  IdDoanhNghiep INT,
  IdHoSo INT,
  NgayUngTuyen DATE,
  ViTriUngTuyen VARCHAR(50),
  DiemDanhGia INT
);

CREATE TABLE PHIEUDANGTUYEN (
  IdPhieuDangTuyen INT IDENTITY(1,1) NOT NULL, 
  ViTriDangTuyen VARCHAR(50),
  SoLuongTuyenDung INT,
  PRIMARY KEY (IdPhieuDangTuyen)
);

CREATE TABLE YEUCAUCV (
  IdYeuCau INT IDENTITY(1,1) NOT NULL, 
  MoTa VARCHAR(1000),
  IdPhieuDangTuyen INT,
  PRIMARY KEY (IdYeuCau)
);

CREATE TABLE PHIEUQUANGCAO (
  IdPhieuQuangCao INT IDENTITY(1,1) NOT NULL, 
  NgayBatDau DATE,
  NgayKetThuc DATE,
  HinhThucDangTuyen VARCHAR(50),
  TongTienQuangCao BIGINT,
  IdPhieuDangTuyen INT,
  PRIMARY KEY (IdPhieuQuangCao)
);

ALTER TABLE UNGVIEN
ADD CONSTRAINT FK_UngVien_ThanhVien FOREIGN KEY (IdThanhVien)
REFERENCES THANHVIEN(IdThanhVien);

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NhanVien_ThanhVien FOREIGN KEY (IdThanhVien)
REFERENCES THANHVIEN(IdThanhVien);

ALTER TABLE THANHTOAN
ADD CONSTRAINT FK_ThanhToan_HoaDon FOREIGN KEY (IdHoaDon)
REFERENCES HOADON(IdHoaDon);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HoaDon_DoanhNghiep FOREIGN KEY (IdDoanhNghiep)
REFERENCES DOANHNGHIEP(IdThanhVien);

ALTER TABLE HOSO
ADD CONSTRAINT FK_HoSo_ThanhVien FOREIGN KEY (IdThanhVien)
REFERENCES THANHVIEN(IdThanhVien);

ALTER TABLE BANGCAP
ADD CONSTRAINT FK_BangCap_HoSo FOREIGN KEY (IdHoSo)
REFERENCES HOSO(IdHoSo);

ALTER TABLE UNGTUYEN
ADD CONSTRAINT FK_UngTuyen_DoanhNghiep FOREIGN KEY (IdDoanhNghiep)
REFERENCES DOANHNGHIEP(IdThanhVien);

ALTER TABLE UNGTUYEN
ADD CONSTRAINT FK_UngTuyen_HoSo FOREIGN KEY (IdHoSo)
REFERENCES HOSO(IdHoSo);

ALTER TABLE YEUCAUCV
ADD CONSTRAINT FK_YeuCauCV_PhieuDangTuyen FOREIGN KEY (IdPhieuDangTuyen)
REFERENCES PHIEUDANGTUYEN(IdPhieuDangTuyen);

ALTER TABLE PHIEUQUANGCAO
ADD CONSTRAINT FK_PhieuQuangCao_PhieuDangTuyen FOREIGN KEY (IdPhieuDangTuyen)
REFERENCES PHIEUDANGTUYEN(IdPhieuDangTuyen);