DROP DATABASE PTTK_ABC;

CREATE DATABASE PTTK_ABC;
GO

USE PTTK_ABC;
GO

CREATE TABLE THANHVIEN (
  IDThanhVien INT IDENTITY(1,1) NOT NULL,
  TenDangNhap VARCHAR(30) UNIQUE,
  Ten VARCHAR(50),
  Email VARCHAR(30),
  MatKhau VARCHAR(20) NOT NULL,
  LoaiThanhVien VARCHAR(20) CHECK (LoaiThanhVien IN ('DOANHNGHIEP', 'UNGVIEN', 'NHANVIEN')),
  PRIMARY KEY (IDThanhVien)
);

CREATE TABLE DOANHNGHIEP (
  IDDoanhNghiep INT PRIMARY KEY,
  MaSoThue INT,
  NguoiDaiDien VARCHAR(50),
  DiaChi VARCHAR(100),
  UuDai FLOAT
);

CREATE TABLE UNGVIEN (
  IDUngVien INT PRIMARY KEY,
  NgaySinh DATE
);

CREATE TABLE NHANVIEN (
  IDNhanVien INT PRIMARY KEY,
  VaiTro VARCHAR(50) CHECK (VaiTro IN ('Ban Lãnh Đạo', 'Nhân Viên Cơ Bản'))
);

CREATE TABLE THANHTOAN (
  IDThanhToan INT IDENTITY(1,1) NOT NULL,
  NgayGiaoDich DATE,
  HinhThucTT VARCHAR(50),
  SoTienCanThanhToan BIGINT,
  Dot INT,
  IDHoaDon INT,
  IDNhanVien INT,
  PRIMARY KEY (IDThanhToan)
);

CREATE TABLE HOADON (
  IDHoaDon INT IDENTITY(1,1) NOT NULL,
  TongTien BIGINT,
  DaTra BIGINT,
  LoaiHinhThanhToan VARCHAR(50),
  NgayLap DATE,
  TrangThaiHoanThanh VARCHAR(50),
  IDDoanhNghiep INT,
  PRIMARY KEY (IDHoaDon)
);

CREATE TABLE BANGCAP (
  IDBang INT IDENTITY(1,1) NOT NULL,
  TenBang VARCHAR(50),
  CapBac VARCHAR(50),
  NgayCap DATE,
  DonViCap VARCHAR(100),
  IDUngVien INT,
  PRIMARY KEY (IDBang)
);

CREATE TABLE HOSOUNGTUYEN (
  IDDoanhNghiep INT,
  IDUngVien INT,
  NgayUngTuyen DATE,
  ViTriUngTuyen VARCHAR(50),
  DiemDanhGia INT
  PRIMARY KEY (IDDoanhNghiep, IDUngVien)
);

CREATE TABLE PHIEUDANGTUYEN (
  IDPhieuDangTuyen INT IDENTITY(1,1) NOT NULL, 
  ViTriDangTuyen VARCHAR(50),
  SoLuongTuyenDung INT,
  IDDoanhNghiep INT,
  IDPhieuQuangCao INT,
  PRIMARY KEY (IDPhieuDangTuyen)
);

CREATE TABLE YEUCAUCV (
  IDYeuCau INT IDENTITY(1,1) NOT NULL, 
  IDPhieuDangTuyen INT,
  MoTa VARCHAR(1000),
  PRIMARY KEY (IDYeuCau, IDPhieuDangTuyen)
);

CREATE TABLE PHIEUQUANGCAO (
  IDPhieuQuangCao INT IDENTITY(1,1) NOT NULL, 
  NgayBatDau DATE,
  NgayKetThuc DATE,
  HinhThucDangTuyen VARCHAR(50),
  TongTienQuangCao BIGINT,
  PRIMARY KEY (IDPhieuQuangCao)
);

ALTER TABLE UNGVIEN ADD 
  CONSTRAINT FK_UNGVIEN_THANHVIEN FOREIGN KEY (IDUngVien) REFERENCES THANHVIEN(IDThanhVien);

ALTER TABLE NHANVIEN ADD 
  CONSTRAINT FK_NHANVIEN_THANHVIEN FOREIGN KEY (IDNhanVien) REFERENCES THANHVIEN(IDThanhVien);

ALTER TABLE DOANHNGHIEP ADD 
  CONSTRAINT FK_DOANHNGHIEP_THANHVIEN FOREIGN KEY (IDDoanhNghiep) REFERENCES THANHVIEN(IDThanhVien);

ALTER TABLE THANHTOAN ADD 
  CONSTRAINT FK_THANHTOAN_HOADON FOREIGN KEY (IDHoaDon) REFERENCES HOADON(IDHoaDon),
  CONSTRAINT FK_THANHTOAN_NHANVIEN FOREIGN KEY (IDNhanVien) REFERENCES NHANVIEN(IDNhanVien);

ALTER TABLE HOADON ADD 
  CONSTRAINT FK_HOADON_DOANHNGHIEP FOREIGN KEY (IDDoanhNghiep) REFERENCES DOANHNGHIEP(IDDoanhNghiep);

ALTER TABLE BANGCAP ADD 
  CONSTRAINT FK_BANGCAP_UNGVIEN FOREIGN KEY (IDUngVien) REFERENCES UNGVIEN(IDUngVien);

ALTER TABLE HOSOUNGTUYEN ADD 
  CONSTRAINT FK_HOSOUNGTUYEN_DOANHNGHIEP FOREIGN KEY (IDDoanhNghiep) REFERENCES DOANHNGHIEP(IDDoanhNghiep),
  CONSTRAINT FK_HOSOUNGTUYEN_UNGVIEN FOREIGN KEY (IDUngVien) REFERENCES UNGVIEN(IDUngVien);

ALTER TABLE PHIEUDANGTUYEN ADD 
  CONSTRAINT FK_PHIEUDANGTUYEN_DOANHNGHIEP FOREIGN KEY (IDDoanhNghiep) REFERENCES DOANHNGHIEP(IDDoanhNghiep),
  CONSTRAINT FK_PHIEUDANGTUYEN_PHIEUQUANGCAO FOREIGN KEY (IDPhieuQuangCao) REFERENCES PHIEUQUANGCAO(IDPhieuQuangCao);

ALTER TABLE YEUCAUCV ADD 
  CONSTRAINT FK_YEUCAUCV_PHIEUDANGTUYEN FOREIGN KEY (IDPhieuDangTuyen) REFERENCES PHIEUDANGTUYEN(IDPhieuDangTuyen);